### PR TITLE
Require explicit options

### LINKED ISSUE #15: MLLP.Reciver does not fail to start when a dispatcher that does not exist is provided
In the case that a  dispatcher module which does not exist the MLLP.Reciver will crash later than it probably  should. 

See examples below. 

# Example 1

In this case where the sender does not send a wrapped message, we'll never see the receiver crash. Non-happy path behavior, but I feel it shouldn't be possible. 

```
iex(1)> {:ok, recv_pid} = MLLP.Receiver.start(9999, DispatcherDoesNotExist)
{:ok,
 %{
   pid: #PID<0.236.0>,
   port: 9999,
   receiver_id: #Reference<0.1637481935.149946377.10110>
 }}
iex(2)>  {:ok, sender_pid} = MLLP.Sender.start_link({127, 0, 0, 1}, 9999)
{:ok, #PID<0.250.0>}
iex(3)> MLLP.Sender.send_raw_and_receive_reply(sender_pid, HL7.Examples.wikipedia_sample_hl7())

12:08:30.146 [debug] Receiver received data: ["MSH|^~\\&|MegaReg|XYZHospC|SuperOE|XYZImgCtr|20060529090131-0500||ADT^A01^ADT_A01|01052901|P|2.5\rEVN||200605290901||||200605290900\rPID|||56782445^^^UAReg^PI||KLEINSAMPLE^BARRY^Q^JR||19620910|M||2028-9^^HL70005^RA99113^^XYZ|260 GOODWIN CREST DRIVE^^BIRMINGHAM^AL^35209^^M~NICKELL’S PICKLES^10000 W 100TH AVE^BIRMINGHAM^AL^35200^^O|||||||0105I30001^^^99DEF^AN\rPV1||I|W^389^1^UABH^^^^3||||12345^MORGAN^REX^J^^^MD^0010^UAMC^L||67890^GRAINGER^LUCY^X^^^MD^0010^UAMC^L|MED|||||A0||13579^POTTER^SHERMAN^T^^^MD^0010^UAMC^L|||||||||||||||||||||||||||200605290900\rOBX|1|N^K&M|^Body Height||1.80|m^Meter^ISO+|||||F\rOBX|2|NM|^Body Weight||79|kg^Kilogram^ISO+|||||F\rAL1|1||^ASPIRIN\rDG1|1||786.50^CHEST PAIN, UNSPECIFIED^I9|||A\r"].

PID|||56782445^^^UAReg^PI||KLEINSAMPLE^BARRY^Q^JR||19620910|M||2028-9^^HL70005^RA99113^^XYZ|260 GOODWIN CREST DRIVE^^BIRMINGHAM^AL^35209^^M~NICKELL’S PICKLES^10000 W 100TH AVE^BIRMINGHAM^AL^35200DG1|1||786.50^CHEST PAIN, UNSPECIFIED^I9|||A|||FFMD^0010^UAMC^L||67890^GRAINGER^LUCY^X^^^MD^0010^UAMC^L|MED|||||A0||13579^POTTER^SHERMAN^T^^^MD^0010^UAMC^L|||||||||||||||||||||||||||200605290900
{:error, %{reason: :timeout, type: :recv_failure}}
iex(4)>
12:08:36.147 [debug] MLLP.Receiver tcp_closed.
```

# Example 2 

In this case, we do crash, but much later than we should. 

```
iex(1)> {:ok, recv_pid} = MLLP.Receiver.start(9999, DispatcherDoesNotExist)
{:ok,
 %{
   pid: #PID<0.236.0>,
   port: 9999,
   receiver_id: #Reference<0.3927097272.686555138.248569>
 }}
iex(2)>  {:ok, sender_pid} = MLLP.Sender.start_link({127, 0, 0, 1}, 9999)
{:ok, #PID<0.250.0>}
iex(3)> MLLP.Sender.send_hl7_and_receive_ack(sender_pid, HL7.Message.new(HL7.Examples.wikipedia_sample_hl7()))

12:09:27.432 [debug] Receiver received data: [<<11, 77, 83, 72, 124, 94, 126, 92, 38, 124, 77, 101, 103, 97, 82, 101, 103, 124, 88, 89, 90, 72, 111, 115, 112, 67, 124, 83, 117, 112, 101, 114, 79, 69, 124, 88, 89, 90, 73, 109, 103, 67, 116, 114, 124, 50, 48, 48, 54, 48, ...>>].

12:09:27.440 [error] GenServer #PID<0.251.0> terminating
** (UndefinedFunctionError) function DispatcherDoesNotExist.dispatch/3 is undefined (module DispatcherDoesNotExist is not available)
    DispatcherDoesNotExist.dispatch(:mllp_hl7, "MSH|^~\\&|MegaReg|XYZHospC|SuperOE|XYZImgCtr|20060529090131-0500||ADT^A01^ADT_A01|01052901|P|2.5\rEVN||200605290901||||200605290900\rPID|||56782445^^^UAReg^PI||KLEINSAMPLE^BARRY^Q^JR||19620910|M||2028-9^^HL70005^RA99113^^XYZ|260 GOODWIN CREST DRIVE^^BIRMINGHAM^AL^35209^^M~NICKELL’S PICKLES^10000 W 100TH AVE^BIRMINGHAM^AL^35200^^O|||||||0105I30001^^^99DEF^AN\rPV1||I|W^389^1^UABH^^^^3||||12345^MORGAN^REX^J^^^MD^0010^UAMC^L||67890^GRAINGER^LUCY^X^^^MD^0010^UAMC^L|MED|||||A0||13579^POTTER^SHERMAN^T^^^MD^0010^UAMC^L|||||||||||||||||||||||||||200605290900\rOBX|1|N^K&M|^Body Height||1.80|m^Meter^ISO+|||||F\rOBX|2|NM|^Body Weight||79|kg^Kilogram^ISO+|||||F\rAL1|1||^ASPIRIN\rDG1|1||786.50^CHEST PAIN, UNSPECIFIED^I9|||A\r", %MLLP.FramingContext{current_message_type: nil, custom_data: %{}, dispatcher_module: DispatcherDoesNotExist, packet_framer_module: MLLP.DefaultPacketFramer, receiver_buffer: "", reply_buffer: ""})
    (elixir_mllp 0.4.5) lib/mllp/default_packet_framer.ex:4: MLLP.DefaultPacketFramer.handle_packet/2
    (elixir_mllp 0.4.5) lib/mllp/receiver.ex:130: MLLP.Receiver.handle_info/2
    (stdlib 3.15.2) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.2) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:tcp, #Port<0.7>, <<11, 77, 83, 72, 124, 94, 126, 92, 38, 124, 77, 101, 103, 97, 82, 101, 103, 124, 88, 89, 90, 72, 111, 115, 112, 67, 124, 83, 117, 112, 101, 114, 79, 69, 124, 88, 89, 90, 73, 109, 103, 67, 116, 114, 124, 50, 48, ...>>}
State: %{client_info: {{127, 0, 0, 1}, 62843}, framing_context: %MLLP.FramingContext{current_message_type: nil, custom_data: %{}, dispatcher_module: DispatcherDoesNotExist, packet_framer_module: MLLP.DefaultPacketFramer, receiver_buffer: "", reply_buffer: ""}, server_info: {{127, 0, 0, 1}, 9999}, socket: #Port<0.7>, transport: :ranch_tcp}
{:error, %{reason: :closed, type: :recv_failure}}
iex(4)>
12:09:27.453 [error] Ranch listener #Reference<0.3927097272.686555138.248569> had connection process started with MLLP.Receiver:start_link/4 at #PID<0.251.0> exit with reason: {:undef, [{DispatcherDoesNotExist, :dispatch, [:mllp_hl7, "MSH|^~\\&|MegaReg|XYZHospC|SuperOE|XYZImgCtr|20060529090131-0500||ADT^A01^ADT_A01|01052901|P|2.5\rEVN||200605290901||||200605290900\rPID|||56782445^^^UAReg^PI||KLEINSAMPLE^BARRY^Q^JR||19620910|M||2028-9^^HL70005^RA99113^^XYZ|260 GOODWIN CREST DRIVE^^BIRMINGHAM^AL^35209^^M~NICKELL’S PICKLES^10000 W 100TH AVE^BIRMINGHAM^AL^35200^^O|||||||0105I30001^^^99DEF^AN\rPV1||I|W^389^1^UABH^^^^3||||12345^MORGAN^REX^J^^^MD^0010^UAMC^L||67890^GRAINGER^LUCY^X^^^MD^0010^UAMC^L|MED|||||A0||13579^POTTER^SHERMAN^T^^^MD^0010^UAMC^L|||||||||||||||||||||||||||200605290900\rOBX|1|N^K&M|^Body Height||1.80|m^Meter^ISO+|||||F\rOBX|2|NM|^Body Weight||79|kg^Kilogram^ISO+|||||F\rAL1|1||^ASPIRIN\rDG1|1||786.50^CHEST PAIN, UNSPECIFIED^I9|||A\r", %MLLP.FramingContext{current_message_type: nil, custom_data: %{}, dispatcher_module: DispatcherDoesNotExist, packet_framer_module: MLLP.DefaultPacketFramer, receiver_buffer: "", reply_buffer: ""}], []}, {MLLP.DefaultPacketFramer, :handle_packet, 2, [file: 'lib/mllp/default_packet_framer.ex', line: 4]}, {MLLP.Receiver, :handle_info, 2, [file: 'lib/mllp/receiver.ex', line: 130]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 695]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 771]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}
```

# Proposed solution 

Ensure the module exists when the receiver is started.

### PR DESCRIPTION
**Pull request by starbelly**
This commit changes start/{1,2,3} to start/1 in favor of requiring the consumer to be intentional and clear in that parameters they provide.

 - Shift port, dispatcher, and packet_framer arguments into a single keyword list argument
 - Require a dispatcher argument
 - Update tests where required
 - Add docs around options for start/1
 - Add ex_doc to the mix
 
 Closes #15

### CODE REVIEW

File: lib/mllp/receiver.ex [hunk 1]
```diff
@@ -62,10 +84,74 @@ defmodule MLLP.Receiver do
...
+      :ranch.child_spec(
+        args.receiver_id,
+        args.transport_mod,
+        args.transport_opts,
+        args.proto_mod,
+        args.proto_opts
+      )
+
+    case res do
+      {id, start, restart, shutdown, type, modules} ->
```
Comment (vikas15bhardwaj) [inline lib/mllp/receiver.ex]: Do we really need this case, we can use pattern match on line 133

File: lib/mllp/receiver.ex [hunk 2]
```diff
@@ -1,4 +1,22 @@
 defmodule MLLP.Receiver do
+  @moduledoc """
```
Comment (vikas15bhardwaj) [inline lib/mllp/receiver.ex:2]: love the documentation 😍

File: mix.exs [hunk 3]
```diff
@@ -34,11 +34,12 @@ defmodule MLLP.MixProject do
       {:telemetry, "~> 0.4.3"},
       {:ranch, "~> 1.7.1"},
       {:elixir_hl7, "~> 0.6.0"},
+      {:ex_doc, "~> 0.24.2", only: :dev, runtime: false},
       {:dialyxir, "~> 1.1.0", only: [:dev, :test], runtime: false},
       {:mix_test_watch, "~> 1.0.2", only: :dev, runtime: false},
       {:mox, "~> 1.0.0", only: :test},
       {:excoveralls, "~> 0.14.0", only: :test, runtime: false},
-      {:private, "~> 0.1.1", runtime: false}
+      {:private, "~> 0.1.1", runtime: false},
```
Comment (vikas15bhardwaj) [inline mix.exs]: `private` dep, TIL. I see you have added its dependency. Are we testing at present private functions.

File: lib/mllp/receiver.ex [hunk 4]
```diff
@@ -79,6 +165,35 @@ defmodule MLLP.Receiver do
      ])}
   end
 
+  defp to_args(opts) do
```
Comment (vikas15bhardwaj) [inline lib/mllp/receiver.ex:165]: I like this, a clean approach to deal with all options. I like that we enforce now default dispatcher. I think, and as you also mentioned earlier, we should rename DefaultDispatcher to EchoDispatcher in a separate PR. In EchoDispatcher, we should remove `Logger.error` message. We should echo the message as info and returns positive ACK. It may require some changes in README as well.

File: mix.exs (hunk 3 above)
Comment (starbelly) [reply mix.exs]: I didn't add  it, it just got moved (i.e, it's in mix.exs in main), but IMO it's not in use, so let's remove it, thoughts?

File: lib/mllp/receiver.ex (hunk 1 above)
Comment (starbelly) [reply lib/mllp/receiver.ex]: Do you mean ... 

`case :ranch.child_spec(...) do  ...` ? 

If so, if I can't fit something into a case expression cleanly, I opt to assign to a variable. I try not to look at variables as a  cost but as a chance to provide the reader more context. In that sense, `res` is a bad name here. wdyt?

Comment (starbelly) [reply lib/mllp/receiver.ex]: Oh, I think you mean  why not just do `{id, start, restart, shutdown, type, modules} = :ranch.child_spec(...)` 

It's because it line wrapped, but I have no  strong feelings and will adjust.

Comment (vikas15bhardwaj) [reply lib/mllp/receiver.ex]: As there is no other case condition, I was thinking like this

```
{id, start, restart, shutdown, type, modules} = :ranch.child_spec(
        args.receiver_id,
        args.transport_mod,
        args.transport_opts,
        args.proto_mod,
        args.proto_opts
      )
```

File: mix.exs (hunk 3 above)
Comment (vikas15bhardwaj) [reply mix.exs]: Oh, I didn't see it in main. I am OK removing it

File: lib/mllp/receiver.ex [hunk 5]
```diff
@@ -62,10 +84,71 @@ defmodule MLLP.Receiver do
...
+          MyRef,
+          :ranch_tcp,
+          %{socket_opts: [port: 4090]},
+          MLLP.Receiver,
+          [packet_framer_module: MLLP.DefaultPacketFramer, dispatcher_module: MLLP.DefaultDispatcher]
+        ]},
+        type: :supervisor
+      }
+  """
+  @spec child_spec(options()) :: Superviosr.child_spec()
```
Comment (vikas15bhardwaj) [inline lib/mllp/receiver.ex]: There is typo in Supervisor. How did dialyzer pass?🤔

Comment (starbelly) [reply lib/mllp/receiver.ex]: Interesting! Looking further before I fix this up.

File: lib/mllp/receiver.ex (hunk 1 above)
Comment (starbelly) [reply lib/mllp/receiver.ex]: Done.

File: lib/mllp/receiver.ex [hunk 6]
```diff
@@ -171,7 +171,14 @@ defmodule MLLP.Receiver do
       Keyword.get(opts, :dispatcher, nil) ||
         raise(ArgumentError, "No dispatcher module provided")
 
+    Code.ensure_loaded?(dispatcher_mod) ||
```
Comment (vikas15bhardwaj) [inline lib/mllp/receiver.ex:174]: Should we also check for if it implements behaviour `MLLP.Dispatcher`

File: lib/mllp/receiver.ex (hunk 5 above)
Comment (starbelly) [reply lib/mllp/receiver.ex]: To note, it's because our dialyzer setup  is strict enough right now. We need to add more flags to the config, but only added `:unknown` for now, as adding the rest will result in a lot of warnings and errors and changes to a lot of files. Doing this should be the next PR imo.

File: lib/mllp/receiver.ex (hunk 6 above)
Comment (starbelly) [reply lib/mllp/receiver.ex:174]: Yup :) Excellent call out!

File: test/receiver_test.exs [hunk 7]
```diff
@@ -13,9 +13,21 @@ defmodule ReceiverTest do
   doctest Receiver
 
   describe "Starting and stopping a receiver" do
+    test "raises no when no port argument provided" do
```
Comment (vikas15bhardwaj) [inline test/receiver_test.exs]: do you have extra "no" in test case description

File: lib/mllp/receiver.ex [hunk 8]
```diff
@@ -62,10 +84,71 @@ defmodule MLLP.Receiver do
...
   end
 
+  @doc """
+  A function which can be used to embed an MLLP.Receiver under Elixir v1.5+ supervisors.
+  Unlike `start/1`, `start/2`, or `start/3` this function takes two additional options : `ref` and `transport_opts`.
+  Note that if a `ref` option is not supplied a reference will be created for you using `make_ref/0`.
+      children = [{MLLP.Receiver, [
+          ref: MyRef,
+          port: 4090,
+          dispatcher: MyDispatcher,
```
Comment (vikas15bhardwaj) [inline lib/mllp/receiver.ex]: Can we change this to `MLLP.DefautDispatcher` and also for packet framer

Comment (starbelly) [reply lib/mllp/receiver.ex]: Yup, it should be... you have hawk eyes my friend!

File: test/receiver_test.exs [hunk 9]
```diff
@@ -12,10 +12,37 @@ defmodule ReceiverTest do
 
   doctest Receiver
 
+  describe "supervsion" do
+    test "successfully starts up under a supervisor using a child spec" do
```
Comment (vikas15bhardwaj) [inline test/receiver_test.exs]: We are not asserting on anything in this test. I think it may be more better to do in integration test, where we can start sender and validate against it. Or we simply can assert on process state. What do you think?

**Review by vikas15bhardwaj — APPROVED** [review]
